### ISSUE TITLE
Does not work with p:PublishSingleFile

### ISSUE THREAD

**Issue by seriouz** [SteveSandersonMS/WebWindow#14]
First of all: This is a great tool, thanks! But when i am building the app like this `dotnet publish -c Release --framework netcoreapp3.0 --runtime win-x64 /p:PublishSingleFile=true` the index.html file cannot be reached. I don't know if this is a problem with the bundler or _in_ the application when the file is being resolved.

**Comment by distantcam** [comment]
The bundler won't include the `wwwroot` folder, and even if it did, it won't know to load the files from somewhere other than the filesystem.

I created a project that embeds the `wwwroot` folder into the assembly and code to let the web windows load files from the assembly when the `app://` schema is used. https://github.com/distantcam/WebWindow.ViewModelExample

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @distantcam!

**Comment by sondreb** [comment]
Here is the solution you can use to find the wwwroot folder when you publish as a single file:

```C#
string directory = System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
var path = System.IO.Path.Combine(directory, "wwwroot", "index.html");
window.NavigateToLocalFile(path);
```

Only tested on Windows, but it is likely this will work on all platforms. Depends perhaps how it is started, and you could change the code to get assembly to find one of your custom classes instead of using the executing assembly.

Example path where single publish file is extracted:

`C:\Users\USER\AppData\Local\Temp\.net\YourAppName\pnlm53kp.ran\`
