### ISSUE TITLE
Add IE support?

### ISSUE THREAD

**Issue by Berrysoft** [SteveSandersonMS/WebWindow#32]
Although the initial idea is to get use of modern browser technology, is there any plan to use IE as back-end on Windows? Some may prefer this because their app may intend to support Windows 7/8.1, and it is heavy to install Edge (Chromium) or download a Chromium core.

**Comment by SteveSandersonMS** [comment]
If this is a relatively small feature, I'd be happy to consider accepting a PR that adds this feature.

I suspect not a lot of developers would want to use it, since supporting IE throws you back into the dark ages of never really knowing what JS/CSS/layout/etc features are actually going to work at runtime.
